import Head from "next/head";
import LoginForm from "../components/auth/LoginForm";

export default function Login() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full flex-1 flex-col items-center justify-center">
        <h1 className="text-lg text-white">Log In</h1>
        <LoginForm />
      </main>
    </>
  );
}
