import Head from "next/head";
import RegisterForm from "../components/auth/RegisterForm";

export default function SignUp() {
  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full flex-1 flex-col items-center justify-center">
        <h1 className="mb-4 text-lg text-white">Sign Up</h1>
        <RegisterForm />
      </main>
    </>
  );
}
