import Head from "next/head";

export default function Unauthorized() {
  return (
    <>
      <Head>
        <title>Unauthorized</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-full flex-1 flex-col items-center justify-center space-y-4 text-white">
        <h1 className="text-4xl font-light">Oops!</h1>
        <p className="text-gray-400">
          You&apos;re not authorized to view this resource.
        </p>
      </div>
    </>
  );
}
